-- -----------------------------------------------------------------------------
-- Job controller configuration
-- SLV_JOB_CONTROLLER_DESC
-- -----------------------------------------------------------------------------

-- Enable identity insert
SET IDENTITY_INSERT SLV_JOB_CONTROLLER_DESC ON

-- Check if configuration exists
IF EXISTS (
	SELECT	1
	FROM		SLV_JOB_CONTROLLER_DESC
	WHERE		SLV_JOB_CONTROLLER_DESC_ID	= #{SLV_JOB_CONTROLLER_DESC_ID}
)
BEGIN
	-- Update existing configuration
	UPDATE	SLV_JOB_CONTROLLER_DESC
	SET			NAME												= '#{NAME}',
					POLLING_SEC									= #{POLLING_SEC},
					SCHEDULING_THREAD_COUNT			= #{SCHEDULING_THREAD_COUNT},
					JOB_READER_QUEUE_SIZE				= #{JOB_READER_QUEUE_SIZE},
					SCHEDULING_QUEUE_SIZE				= #{SCHEDULING_QUEUE_SIZE},
					CT_SEL_WRITER_QUEUE_SIZE		= #{CT_SEL_WRITER_QUEUE_SIZE},
					CT_SEL_WRITER_THREAD_COUNT	= #{CT_SEL_WRITER_THREAD_COUNT},
					OUTPUT_SVC_QUEUE_SIZE				= #{OUTPUT_SVC_QUEUE_SIZE},
					CT_SCHED_REPOSITORY_SIZE		= #{CT_SCHED_REPOSITORY_SIZE},
					HOSTNAME										= '#{HOSTNAME}',
					DG_CACHE_ENABLED						= #{DG_CACHE_ENABLED},
					DG_CACHE_EVICTION						= #{DG_CACHE_EVICTION},
					DG_CACHE_FILE_SIZE					= #{DG_CACHE_FILE_SIZE},
					DG_CACHE_TEMP_DIR						= #{DG_CACHE_TEMP_DIR},
					DG_CACHE_MAX_DG							= #{DG_CACHE_MAX_DG},
					DG_CACHE_MIN_CT							= #{DG_CACHE_MIN_CT},
					IMPORT_THREAD_POOL_SIZE			= #{IMPORT_THREAD_POOL_SIZE},
					VERSION_KEY									= -1,
					LAST_UPDATE									=	CURRENT_TIMESTAMP,
					USER_UPDATE									= CURRENT_USER
	WHERE		SLV_JOB_CONTROLLER_DESC_ID	= #{SLV_JOB_CONTROLLER_DESC_ID}
END
ELSE
BEGIN
	-- Create new configuration
	INSERT INTO	SLV_JOB_CONTROLLER_DESC (SLV_JOB_CONTROLLER_DESC_ID, LAST_UPDATE, USER_UPDATE, VERSION_KEY, NAME, POLLING_SEC, SCHEDULING_THREAD_COUNT, JOB_READER_QUEUE_SIZE, SCHEDULING_QUEUE_SIZE, CT_SEL_WRITER_QUEUE_SIZE, CT_SEL_WRITER_THREAD_COUNT, OUTPUT_SVC_QUEUE_SIZE, CT_SCHED_REPOSITORY_SIZE, HOSTNAME, DG_CACHE_ENABLED, DG_CACHE_EVICTION, DG_CACHE_FILE_SIZE, DG_CACHE_TEMP_DIR, DG_CACHE_MAX_DG, DG_CACHE_MIN_CT, IMPORT_THREAD_POOL_SIZE)
	VALUES (
		#{SLV_JOB_CONTROLLER_DESC_ID},
		CURRENT_TIMESTAMP,
		CURRENT_USER,
		-1,
		'#{NAME}',
		#{POLLING_SEC},
		#{SCHEDULING_THREAD_COUNT},
		#{JOB_READER_QUEUE_SIZE},
		#{SCHEDULING_QUEUE_SIZE},
		#{CT_SEL_WRITER_QUEUE_SIZE},
		#{CT_SEL_WRITER_THREAD_COUNT},
		#{OUTPUT_SVC_QUEUE_SIZE},
		#{CT_SCHED_REPOSITORY_SIZE},
		'#{HOSTNAME}',
		#{DG_CACHE_ENABLED},
		#{DG_CACHE_EVICTION},
		#{DG_CACHE_FILE_SIZE},
		#{DG_CACHE_TEMP_DIR},
		#{DG_CACHE_MAX_DG},
		#{DG_CACHE_MIN_CT},
		#{IMPORT_THREAD_POOL_SIZE}
	)
END

-- Disable identity insert
SET IDENTITY_INSERT SLV_JOB_CONTROLLER_DESC OFF
