-- -----------------------------------------------------------------------------
-- TESS configuration
-- SLV_TESS_DESC
-- -----------------------------------------------------------------------------

-- Enable identity insert
SET IDENTITY_INSERT SLV_TESS_DESC ON

-- Check if configuration exists
IF EXISTS (
	SELECT	1
	FROM		SLV_TESS_DESC
	WHERE		SLV_TESS_DESC_ID					= #{SLV_TESS_DESC_ID}
)
BEGIN
	-- Update existing configuration
	UPDATE	SLV_TESS_DESC
	SET			HOSTNAME									= '#{HOSTNAME}',
					NAME											= '#{NAME}',
					SHARED_FILESYSTEM_ROOT		= '#{SHARED_FILESYSTEM_ROOT}',
					FTP_PORT									= #{FTP_PORT},
					PASSIVE_PORTS							= #{PASSIVE_PORTS},
					FTP_MAX_CONCURRENT_LOGINS	= #{FTP_MAX_CONCURRENT_LOGINS},
					FTP_MAX_LOGIN_FAILURES		= #{FTP_MAX_LOGIN_FAILURES},
					FTP_LOGIN_FAILURE_DELAY		= #{FTP_LOGIN_FAILURE_DELAY},
					INITIAL_PORT							= #{INITIAL_PORT},
					FTP_PASSIVE_MODE					= #{FTP_PASSIVE_MODE},
					VERSION_KEY								= -1,
					LAST_UPDATE								=	CURRENT_TIMESTAMP,
					USER_UPDATE								= CURRENT_USER
	WHERE		SLV_TESS_DESC_ID					= #{SLV_TESS_DESC_ID}
END
ELSE
BEGIN
	-- Create new configuration
	INSERT INTO	SLV_TESS_DESC (SLV_TESS_DESC_ID, USER_UPDATE, LAST_UPDATE, VERSION_KEY, NAME, HOSTNAME, SHARED_FILESYSTEM_ROOT, FTP_PORT, PASSIVE_PORTS, FTP_MAX_CONCURRENT_LOGINS, FTP_MAX_LOGIN_FAILURES, FTP_LOGIN_FAILURE_DELAY, INITIAL_PORT, FTP_PASSIVE_MODE)
	VALUES (
		#{SLV_TESS_DESC_ID},
		CURRENT_USER,
		CURRENT_TIMESTAMP,
		-1,
		'#{NAME}',
		'#{HOSTNAME}',
		'#{SHARED_FILESYSTEM_ROOT}',
		#{FTP_PORT},
		#{PASSIVE_PORTS},
		#{FTP_MAX_CONCURRENT_LOGINS},
		#{FTP_MAX_LOGIN_FAILURES},
		#{FTP_LOGIN_FAILURE_DELAY},
		#{INITIAL_PORT},
		#{FTP_PASSIVE_MODE}
	)
END

-- Disable identity insert
SET IDENTITY_INSERT SLV_TESS_DESC OFF
